debug: false

server-groups:
  group1:
    - server1
    - server2

spy-servers:
  - spyserver1
  - spyserver2

isolate-unlisted-servers: false

disable-order-expression: 'player.server == "disabledserver3"'

order-update-interval: 5000

order:
  - type: ASC
    expression: "player.username"

collision-rule: never
